export let ICONS = [
    "/img/icons/Apple-96.png",
    "/img/icons/Asparagus-96.png",
    "/img/icons/Avocado-96.png",
    "/img/icons/Banana-96.png",
    "/img/icons/Barley-96.png",
    "/img/icons/Beet-96.png",
    "/img/icons/Broccoli-96.png",
    "/img/icons/Cabbage-96.png",
    "/img/icons/cabbage.png",
    "/img/icons/Carrot-96.png",
    "/img/icons/Celery-96.png",
    "/img/icons/Cherry-96.png",
    "/img/icons/Chili Pepper-96.png",
    "/img/icons/Citrus-96.png",
    "/img/icons/Coniferous Tree-96.png",
    "/img/icons/Corn-96.png",
    "/img/icons/Cucumber-96.png",
    "/img/icons/Deciduous Tree-96.png",
    "/img/icons/Dragon Fruit-96.png",
    "/img/icons/Eggplant-96.png",
    "/img/icons/Flower-96.png",
    "/img/icons/Garlic-96.png",
    "/img/icons/Grapes-96.png",
    "/img/icons/Grass-96.png",
    "/img/icons/Hazelnut-96.png",
    "/img/icons/Hops-96.png",
    "/img/icons/Kiwi-96.png",
    "/img/icons/Kohlrabi-96.png",
    "/img/icons/Leek-96.png",
    "/img/icons/Lettuce-96.png",
    "/img/icons/Maple Leaf-96.png",
    "/img/icons/Melon-96.png",
    "/img/icons/Mushroom-96.png",
    "/img/icons/Natural Food-96.png",
    "/img/icons/Nut-96.png",
    "/img/icons/Oak Leaf-96.png",
    "/img/icons/Olive-96.png",
    "/img/icons/Onion-96.png",
    "/img/icons/Palm Tree-96.png",
    "/img/icons/Paprika-96.png",
    "/img/icons/Peach-96.png",
    "/img/icons/Peanuts-96.png",
    "/img/icons/Pear-96.png",
    "/img/icons/Peas-96.png",
    "/img/icons/Pineapple-96.png",
    "/img/icons/Plum-96.png",
    "/img/icons/Pomegranate-96.png",
    "/img/icons/Potato-96.png",
    "/img/icons/Radish-96.png",
    "/img/icons/Raspberry-96.png",
    "/img/icons/Sesame-96.png",
    "/img/icons/Soy-96.png",
    "/img/icons/Spring-96.png",
    "/img/icons/Sprout-96.png",
    "/img/icons/Strawberry-96.png",
    "/img/icons/Sweet Potato-96.png",
    "/img/icons/Tomato-96.png",
    "/img/icons/Watermelon-96.png",
    "/img/icons/Wheat-96.png"
];
