export let ICONS = [
    "/icons/Apple-96.png",
    "/icons/Asparagus-96.png",
    "/icons/Avocado-96.png",
    "/icons/Banana-96.png",
    "/icons/Barley-96.png",
    "/icons/Beet-96.png",
    "/icons/Broccoli-96.png",
    "/icons/Cabbage-96.png",
    "/icons/cabbage.png",
    "/icons/Carrot-96.png",
    "/icons/Celery-96.png",
    "/icons/Cherry-96.png",
    "/icons/Chili Pepper-96.png",
    "/icons/Citrus-96.png",
    "/icons/Coniferous Tree-96.png",
    "/icons/Corn-96.png",
    "/icons/Cucumber-96.png",
    "/icons/Deciduous Tree-96.png",
    "/icons/Dragon Fruit-96.png",
    "/icons/Eggplant-96.png",
    "/icons/Flower-96.png",
    "/icons/Garlic-96.png",
    "/icons/Grapes-96.png",
    "/icons/Grass-96.png",
    "/icons/Hazelnut-96.png",
    "/icons/Hops-96.png",
    "/icons/Kiwi-96.png",
    "/icons/Kohlrabi-96.png",
    "/icons/Leek-96.png",
    "/icons/Lettuce-96.png",
    "/icons/Maple Leaf-96.png",
    "/icons/Melon-96.png",
    "/icons/Mushroom-96.png",
    "/icons/Natural Food-96.png",
    "/icons/Nut-96.png",
    "/icons/Oak Leaf-96.png",
    "/icons/Olive-96.png",
    "/icons/Onion-96.png",
    "/icons/Palm Tree-96.png",
    "/icons/Paprika-96.png",
    "/icons/Peach-96.png",
    "/icons/Peanuts-96.png",
    "/icons/Pear-96.png",
    "/icons/Peas-96.png",
    "/icons/Pineapple-96.png",
    "/icons/Plum-96.png",
    "/icons/Pomegranate-96.png",
    "/icons/Potato-96.png",
    "/icons/Radish-96.png",
    "/icons/Raspberry-96.png",
    "/icons/Sesame-96.png",
    "/icons/Soy-96.png",
    "/icons/Spring-96.png",
    "/icons/Sprout-96.png",
    "/icons/Strawberry-96.png",
    "/icons/Sweet Potato-96.png",
    "/icons/Tomato-96.png",
    "/icons/Watermelon-96.png",
    "/icons/Wheat-96.png"
];
